/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sanpedroproyect;
import DATABASE.ConnectionDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.hsqldb.Library;

/**
 *
 * @author Ivan Mosquera
 */
public class Ingreso_Nuevo_Perfil extends javax.swing.JFrame {
    private String nuevo_perfil;
    private int nuevo_IdPerfil;
    private int nuevo_IdPermiso;
    /**
     * Creates new form Ingreso_Nuevo_Perfil
     */
    public Ingreso_Nuevo_Perfil() {
        initComponents();
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_nombrePerfil = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ckbox_Facturar = new javax.swing.JCheckBox();
        ckbox_Separar = new javax.swing.JCheckBox();
        ckbox_Anular = new javax.swing.JCheckBox();
        ckbox_registrarCliente = new javax.swing.JCheckBox();
        ckbox_reporteCierreCaja = new javax.swing.JCheckBox();
        ckbox_ingresarProducto = new javax.swing.JCheckBox();
        ckbox_ingresarInventario = new javax.swing.JCheckBox();
        ckbox_modificarCliente = new javax.swing.JCheckBox();
        ckbox_realizarDescuentos = new javax.swing.JCheckBox();
        btn_guardarPerfil = new javax.swing.JButton();
        btn_limpiarPerfil = new javax.swing.JButton();
        btn_salirPerfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel11.setText("Ingresar Nuevo Perfil");

        jLabel12.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel12.setText("Nombre");

        jLabel13.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel13.setText("Permisos");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ckbox_Facturar.setText("Facturar");

        ckbox_Separar.setText("Realizar Separados");

        ckbox_Anular.setText("Anular factura");

        ckbox_registrarCliente.setText("Registrar cliente");

        ckbox_reporteCierreCaja.setText("Generar reportes Cierre de caja");

        ckbox_ingresarProducto.setText("Ingresar producto");

        ckbox_ingresarInventario.setText("Ingresar inventario");

        ckbox_modificarCliente.setText("Modificar o eliminar cliente");

        ckbox_realizarDescuentos.setText("Realizar descuentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbox_realizarDescuentos)
                    .addComponent(ckbox_reporteCierreCaja)
                    .addComponent(ckbox_ingresarProducto)
                    .addComponent(ckbox_ingresarInventario)
                    .addComponent(ckbox_modificarCliente)
                    .addComponent(ckbox_registrarCliente)
                    .addComponent(ckbox_Anular)
                    .addComponent(ckbox_Separar)
                    .addComponent(ckbox_Facturar))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ckbox_Facturar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbox_Separar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbox_Anular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbox_registrarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbox_modificarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbox_ingresarInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbox_ingresarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbox_reporteCierreCaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbox_realizarDescuentos)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btn_guardarPerfil.setFont(new java.awt.Font("Bookman Old Style", 1, 11)); // NOI18N
        btn_guardarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disco-flexible (1).png"))); // NOI18N
        btn_guardarPerfil.setText("Guardar");
        btn_guardarPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_guardarPerfil.setMaximumSize(new java.awt.Dimension(60, 65));
        btn_guardarPerfil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_guardarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarPerfilActionPerformed(evt);
            }
        });

        btn_limpiarPerfil.setFont(new java.awt.Font("Bookman Old Style", 1, 11)); // NOI18N
        btn_limpiarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/escoba.png"))); // NOI18N
        btn_limpiarPerfil.setText("Limpiar");
        btn_limpiarPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_limpiarPerfil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_limpiarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarPerfilActionPerformed(evt);
            }
        });

        btn_salirPerfil.setFont(new java.awt.Font("Bookman Old Style", 1, 11)); // NOI18N
        btn_salirPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida (2).png"))); // NOI18N
        btn_salirPerfil.setText("Salir");
        btn_salirPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_salirPerfil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_salirPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel11))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(93, 93, 93)
                            .addComponent(btn_guardarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(81, 81, 81)
                            .addComponent(btn_limpiarPerfil)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_salirPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addGap(71, 71, 71)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_nombrePerfil)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel11)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_nombrePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_limpiarPerfil)
                    .addComponent(btn_guardarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salirPerfil))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void limpiar(){
        txt_nombrePerfil.setText("");
        ckbox_Anular.setSelected(false);
        ckbox_Facturar.setSelected(false);
        ckbox_Separar.setSelected(false);
        ckbox_ingresarInventario.setSelected(false);
        ckbox_ingresarProducto.setSelected(false);
        ckbox_modificarCliente.setSelected(false);
        ckbox_realizarDescuentos.setSelected(false);
        ckbox_reporteCierreCaja.setSelected(false);
        ckbox_registrarCliente.setSelected(false);
    } 
    
    public String Ingresar_perfil(){
        String resul = null , lats = null;
        ConnectionDB cc = new ConnectionDB();
        Connection cn = cc.getConnection();
        PreparedStatement pst =null;
        String sql = "INSERT INTO rol values(null,?)";
        try{
            pst = cn.prepareStatement(sql);
            pst.setString(1,nuevo_perfil);
            pst.execute();
            resul = "Perfil Ingresado Correctamente";
            System.out.println(resul);
            
        }catch(SQLException e){
            resul = "Error : "+e; 
            System.out.println(resul);
            System.out.println(pst);
        }
        
        return resul;
    }
    
    public void obtener_IdRol(){
        ConnectionDB cc = new ConnectionDB();
        Connection cn = cc.getConnection();
        PreparedStatement pst =null;
        ResultSet rs = null;
        try{
            String sql = ("SELECT id_Rol FROM rol WHERE detalle='"+nuevo_perfil+"'");
            pst = cn.prepareStatement(sql);
            rs =pst.executeQuery();
            if (rs.next()){
                    System.out.println(rs.getInt("id_Rol"));
                    nuevo_IdPerfil = rs.getInt("id_Rol");
                }

            } catch (Exception ex){
                    System.out.println(ex);
            }
    }
    
    public void obtener_IdPermiso(String permiso){
        ConnectionDB cc = new ConnectionDB();
        Connection cn = cc.getConnection();
        PreparedStatement pst =null;
        ResultSet rs = null;
        try{
            String sql = ("SELECT id_Permiso FROM permisos WHERE Nombre='"+permiso+"'");
            pst = cn.prepareStatement(sql);
            rs =pst.executeQuery();
            if (rs.next()){
                    System.out.println(rs.getInt("id_Permiso"));
                    nuevo_IdPermiso = rs.getInt("id_Permiso");
                }

            } catch (Exception ex){
                    System.out.println(ex);
            }
    }
    
    public String Ingresar_permisos(int id_permiso){
        String resul = null , lats = null;
        ConnectionDB cc = new ConnectionDB();
        Connection cn = cc.getConnection();
        PreparedStatement pst =null;
        String sql = "INSERT INTO roles_permisos values(?,?)";
        try{
            pst = cn.prepareStatement(sql);
            pst.setInt(1,nuevo_IdPerfil);
            pst.setInt(2,id_permiso);
            pst.execute();
            resul = "Permiso Ingresados Correctamente";
            System.out.println(resul);
            
        }catch(SQLException e){
            resul = "Error : "+e; 
            System.out.println(resul);
            System.out.println(pst);
        }
        
        return resul;
    }
    
    private void btn_guardarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarPerfilActionPerformed
        // TODO add your handling code here:
        nuevo_perfil = txt_nombrePerfil.getText();
        String msj = Ingresar_perfil();
        obtener_IdRol();
        if(ckbox_Facturar.isSelected()){
            obtener_IdPermiso("Facturar");
            Ingresar_permisos(nuevo_IdPermiso);
        }; 
        if(ckbox_Separar.isSelected()){
            obtener_IdPermiso("RealizarSeparados");
            Ingresar_permisos(nuevo_IdPermiso);
        }; 
        if(ckbox_Anular.isSelected()){
            obtener_IdPermiso("Anular");
            Ingresar_permisos(nuevo_IdPermiso);
        };
        if(ckbox_registrarCliente.isSelected()){
            obtener_IdPermiso("RegistrarCliente");
            Ingresar_permisos(nuevo_IdPermiso);
        };
        if(ckbox_modificarCliente.isSelected()){
            obtener_IdPermiso("ModificarCliente");
            Ingresar_permisos(nuevo_IdPermiso);
        };
        if(ckbox_ingresarInventario.isSelected()){
            obtener_IdPermiso("IngresoInventario");
            Ingresar_permisos(nuevo_IdPermiso);
        };
        if(ckbox_ingresarProducto.isSelected()){
            obtener_IdPermiso("IngresarProducto");
            Ingresar_permisos(nuevo_IdPermiso);
        };
        if(ckbox_reporteCierreCaja.isSelected()){
            obtener_IdPermiso("GenerarReportesCierreDeCaja");
            Ingresar_permisos(nuevo_IdPermiso);
        };
        if(ckbox_realizarDescuentos.isSelected()){
            obtener_IdPermiso("RealizarDescuentos");
            Ingresar_permisos(nuevo_IdPermiso);
        };
        if(msj.equals("Perfil Ingresado Correctamente")){
            JOptionPane.showMessageDialog(null, msj , "Guardado Exitoso" , JOptionPane.INFORMATION_MESSAGE);
            limpiar();
        }else{
            JOptionPane.showMessageDialog(null, "REVISAR QUE TODOS LOS CAMPOS ESTÉN CORRECTOS" , "INCORRECTO" , JOptionPane.ERROR_MESSAGE);
        }
        
        /*
        user.nombre = txt_nombre.getText();
        user.cedula = txt_cedula.getText();
        user.usuario = txt_usuario.getText();
        user.contraseña = txt_password.getText();
        int id_rol = cb_selectRol.getSelectedIndex();
        System.out.println(id_rol);
        user.id_Rol = id_rol;
        String msj = Ingresar_usuario();
        if(msj.equals("Usuario Ingresado Correctamente")){
            JOptionPane.showMessageDialog(null, msj , "Guardado Exitoso" , JOptionPane.INFORMATION_MESSAGE);
            limpiar();
        }else{
            JOptionPane.showMessageDialog(null, "REVISAR QUE TODOS LOS CAMPOS ESTÉN CORRECTOS" , "INCORRECTO" , JOptionPane.ERROR_MESSAGE);
        }
        //JOptionPane.showMessageDialog(null, "InfoBox: " + msj , "Guardado Exitoso" , JOptionPane.INFORMATION_MESSAGE);
        //limpiar();*/
    }//GEN-LAST:event_btn_guardarPerfilActionPerformed

    private void btn_limpiarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarPerfilActionPerformed
        limpiar();
    }//GEN-LAST:event_btn_limpiarPerfilActionPerformed

    private void btn_salirPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirPerfilActionPerformed
        Main_Menu ventana_menuPrincipal = new Main_Menu();
        ventana_menuPrincipal.setVisible(true);
        ventana_menuPrincipal.setLocationRelativeTo(null);
        ventana_menuPrincipal.setResizable(false);
        dispose();
    }//GEN-LAST:event_btn_salirPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Nuevo_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Nuevo_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Nuevo_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso_Nuevo_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso_Nuevo_Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardarPerfil;
    private javax.swing.JButton btn_limpiarPerfil;
    private javax.swing.JButton btn_salirPerfil;
    private javax.swing.JCheckBox ckbox_Anular;
    private javax.swing.JCheckBox ckbox_Facturar;
    private javax.swing.JCheckBox ckbox_Separar;
    private javax.swing.JCheckBox ckbox_ingresarInventario;
    private javax.swing.JCheckBox ckbox_ingresarProducto;
    private javax.swing.JCheckBox ckbox_modificarCliente;
    private javax.swing.JCheckBox ckbox_realizarDescuentos;
    private javax.swing.JCheckBox ckbox_registrarCliente;
    private javax.swing.JCheckBox ckbox_reporteCierreCaja;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_nombrePerfil;
    // End of variables declaration//GEN-END:variables
}
