/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sanpedroproyect;

import Class.Mirender;
import Class.Operaciones;
import Class.Prenda;
import Class.Reporte_Operaciones;
import java.awt.event.KeyAdapter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Ivan Mosquera
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    Operaciones op = new Operaciones();
    DefaultTableModel modelotabla = new DefaultTableModel();
    Reporte_Operaciones rop = new Reporte_Operaciones();
    
    
    
    Operaciones op2 = new Operaciones();
    DefaultTableModel modelotabla2 = new DefaultTableModel();
    Reporte_Operaciones rop2 = new Reporte_Operaciones();
    Prenda p = new Prenda();
    public Reportes() {
        initComponents();
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setLocationRelativeTo(null);
        //jTabbedPane1.setEnabledAt(0, false);
        //jTabbedPane1.setEnabledAt(1, false);
        //jTabbedPane1.setEnabledAt(2, false);
         /* TAB 1: REPORTE DE INVENTARIO */
            cb_producto_inv.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(java.awt.event.KeyEvent e) {
                 //To change body of generated methods, choose Tools | Templates.
                String cadena = cb_producto_inv.getEditor().getItem().toString();   
                if(e.getKeyCode()>= 65 && e.getKeyCode()<= 90 || e.getKeyCode()>= 96 && e.getKeyCode()<= 105 || e.getKeyCode()>= 96 && e.getKeyCode()== 8 ){
                    cb_producto_inv.setModel(op.geLista_Producto(cadena));
                    if(cb_producto_inv.getItemCount()>0){
                        cb_producto_inv.showPopup();
                        if(e.getKeyCode()!=8){
                            ((JTextComponent)cb_producto_inv.getEditor().getEditorComponent()).select(cadena.length(),cb_producto_inv.getEditor().getItem().toString().length());
                            
                            
                        }else{
                            cb_producto_inv.getEditor().setItem(cadena);
                            
                        }
                            
                    }else{
                        cb_producto_inv.addItem(cadena);
                    }
                }
            }
            });           
        /*  FIN TAB1           */
        
            
            
        /* TAB2: REPORTE DE SEPARADOS */
        
        DefaultTableModel m  = new DefaultTableModel();
        Reporte_Operaciones rp = new Reporte_Operaciones();
        m = rp.consultar_Separados();
        Tbl_separado.setDefaultRenderer(Object.class, new Mirender());
        Tbl_separado.setModel(m);
        
        /*    FIN TAB2       */
        
        
        
        /* TAB3: REPORTE DE INVENTARIOS TOTALES     */
        
         cb_producto_inv_totales.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(java.awt.event.KeyEvent e) {
                 //To change body of generated methods, choose Tools | Templates.
                String cadena = cb_producto_inv_totales.getEditor().getItem().toString();   
                if(e.getKeyCode()>= 65 && e.getKeyCode()<= 90 || e.getKeyCode()>= 96 && e.getKeyCode()<= 105 || e.getKeyCode()>= 96 && e.getKeyCode()== 8 ){
                    cb_producto_inv_totales.setModel(op2.geLista_Producto(cadena));
                    if(cb_producto_inv_totales.getItemCount()>0){
                        cb_producto_inv_totales.showPopup();
                        if(e.getKeyCode()!=8){
                            ((JTextComponent)cb_producto_inv_totales.getEditor().getEditorComponent()).select(cadena.length(),cb_producto_inv_totales.getEditor().getItem().toString().length());
                            
                            
                        }else{
                            cb_producto_inv_totales.getEditor().setItem(cadena);
                            
                        }
                            
                    }else{
                        cb_producto_inv_totales.addItem(cadena);
                    }
                }
            }
            });      
             
        String nombre_fil = cb_producto_inv_totales.getEditor().getItem().toString();
        modelotabla2 = p.consultar_Producto_total();
        table_repor_inv_totales.setModel(modelotabla2);
        
        /*   FIN TAB 3     */
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tbl_separado1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_repor_inv = new javax.swing.JTable();
        Btn_consultar_report_inventario = new javax.swing.JButton();
        cb_producto_inv = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cb_Talla = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cb_mov = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_separado = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_repor_inv_totales = new javax.swing.JTable();
        Btn_consultar_report_inventarios_totales = new javax.swing.JButton();
        cb_producto_inv_totales = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_Talla_inv_totales = new javax.swing.JComboBox();
        rb_Producto = new javax.swing.JRadioButton();
        rb_talla = new javax.swing.JRadioButton();
        rb_categoria = new javax.swing.JRadioButton();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        Tbl_separado1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Tbl_separado1);

        jLabel2.setText("Reporte Separados");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(451, 451, 451)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(99, 99, 99)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SAMPEDRO S.A.");

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("REPORTE DE INVENTARIO");

        table_repor_inv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(table_repor_inv);

        Btn_consultar_report_inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busqueda.png"))); // NOI18N
        Btn_consultar_report_inventario.setText("Consultar");
        Btn_consultar_report_inventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_consultar_report_inventario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Btn_consultar_report_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_consultar_report_inventarioActionPerformed(evt);
            }
        });

        cb_producto_inv.setEditable(true);

        jLabel4.setText("Producto");

        jLabel5.setText("Talla");

        cb_Talla.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "XS", "S", "M", "L", "XL","" }));

        jLabel6.setText("Movimiento");

        cb_mov.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "","INGRESO","SALIDA","SEPARADO"}));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(96, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(jLabel3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cb_Talla, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_consultar_report_inventario)
                                .addGap(198, 198, 198))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_producto_inv, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_mov, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_producto_inv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Btn_consultar_report_inventario)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cb_mov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(cb_Talla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reporte de Inventario", jPanel5);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Tbl_separado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tbl_separado);

        jLabel1.setText("Reporte Separados");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(451, 451, 451)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(99, 99, 99)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reporte de Separados", jPanel3);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("REPORTE DE INVENTARIO");

        table_repor_inv_totales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Talla", "Categoria", "Cantidad"
            }
        ));
        jScrollPane4.setViewportView(table_repor_inv_totales);

        Btn_consultar_report_inventarios_totales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busqueda.png"))); // NOI18N
        Btn_consultar_report_inventarios_totales.setText("Consultar");
        Btn_consultar_report_inventarios_totales.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_consultar_report_inventarios_totales.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Btn_consultar_report_inventarios_totales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_consultar_report_inventarios_totalesActionPerformed(evt);
            }
        });

        cb_producto_inv_totales.setEditable(true);

        jLabel8.setText("Producto");

        jLabel9.setText("Talla");

        cb_Talla_inv_totales.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "XS", "S", "M", "L", "XL","" }));

        rb_Producto.setText("Por Producto");

        rb_talla.setText("Por Talla");

        rb_categoria.setText("Por Categoria");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(96, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(jLabel7))
                            .addComponent(rb_Producto)
                            .addComponent(rb_talla))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_consultar_report_inventarios_totales)
                        .addGap(198, 198, 198))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_categoria)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(52, 52, 52)
                                .addComponent(cb_producto_inv_totales, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(216, 216, 216)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(cb_Talla_inv_totales, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_producto_inv_totales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(cb_Talla_inv_totales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_consultar_report_inventarios_totales)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rb_Producto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_talla)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_categoria)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inventarios Totales", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void Btn_consultar_report_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_consultar_report_inventarioActionPerformed
        // TODO add your handling code here:
        if(cb_producto_inv.getEditor().getItem().equals("")&&cb_Talla.getSelectedItem().toString().equals("")){
            JOptionPane.showMessageDialog(null, "INGRESE PRODUCTO A REVISAR", "ERROR" , JOptionPane.INFORMATION_MESSAGE);

        }
        String talla =  cb_Talla.getSelectedItem().toString();
        String mov = cb_mov.getSelectedItem().toString();
        System.out.println("Talla : " + talla);
        if(talla.equals("")&&mov.equals("")){
            System.out.println("Entre Aqui");
            String nombre_fil = cb_producto_inv.getEditor().getItem().toString();
            modelotabla = rop.consultar_inventario_filter_nombre(nombre_fil);
            table_repor_inv.setModel(modelotabla);

        }else if(mov.equals("")){
            String nombre_file = cb_producto_inv.getEditor().getItem().toString();
            String talla_fil = cb_Talla.getSelectedItem().toString();
            modelotabla = rop.consultar_inventario_filter_talla(nombre_file, talla_fil);
            table_repor_inv.setModel(modelotabla);

        }else{
            String nombre_file = cb_producto_inv.getEditor().getItem().toString();
            String talla_fil = cb_Talla.getSelectedItem().toString();
            modelotabla = rop.consultar_inventario_filter_talla_mov(nombre_file,talla_fil,mov );
            table_repor_inv.setModel(modelotabla);
        }

    }//GEN-LAST:event_Btn_consultar_report_inventarioActionPerformed

    private void Btn_consultar_report_inventarios_totalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_consultar_report_inventarios_totalesActionPerformed
        // TODO add your handling code here:
        if(cb_producto_inv_totales.getEditor().getItem().equals("")&&cb_Talla_inv_totales.getSelectedItem().toString().equals("")){
            JOptionPane.showMessageDialog(null, "INGRESE PRODUCTO A REVISAR", "ERROR" , JOptionPane.INFORMATION_MESSAGE);

        }
        String talla =  cb_Talla_inv_totales.getSelectedItem().toString();
        System.out.println("Talla : " + talla);
        if(talla.equals("")){
            System.out.println("Entre Aqui");
            String nombre_fil = cb_producto_inv_totales.getEditor().getItem().toString();
            modelotabla2 = rop2.consultar_inventario_filter_nombre(nombre_fil);
            table_repor_inv_totales.setModel(modelotabla2);
        }

    }//GEN-LAST:event_Btn_consultar_report_inventarios_totalesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_consultar_report_inventario;
    private javax.swing.JButton Btn_consultar_report_inventarios_totales;
    private javax.swing.JTable Tbl_separado;
    private javax.swing.JTable Tbl_separado1;
    private javax.swing.JComboBox cb_Talla;
    private javax.swing.JComboBox cb_Talla_inv_totales;
    private javax.swing.JComboBox cb_mov;
    private javax.swing.JComboBox cb_producto_inv;
    private javax.swing.JComboBox cb_producto_inv_totales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rb_Producto;
    private javax.swing.JRadioButton rb_categoria;
    private javax.swing.JRadioButton rb_talla;
    private javax.swing.JTable table_repor_inv;
    private javax.swing.JTable table_repor_inv_totales;
    // End of variables declaration//GEN-END:variables
}
